### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by willzeng274** [willzeng274/shopivy#3]
- [x] add a proper background to `not-found.tsx` (cool animated background, use some animation but cannot have load time/flashing, so javascript shouldn't really be involved)
- [ ] mobile friendly (underway)
- [ ] implement `/dashboard/shop` and `/dashboard/cart` (underway)
- implement proper caching and revalidation mechanisms (HARD, priority)
  - prevent RSC from running more than once (unless absolutely necessary) and fetch new data on the client
  - proper client-side state management (*quantity state is messed up at the moment)
  - proper server-side state management (and passing to server actions)
- finish implementing `Command.tsx`
  - [ ] custom navigation command with router.push to avoid re-fetching user data
- add `/dashboard/settings`
  - [ ] dark mode toggle in `settings`
    - [ ] migrate to using CSS variables for better theming
- display fetched information in frontend
  - [x] main page
  - [x] shop page
  - [x] cart page
- other functionalities to implement: ~~`cart:CRUD`~~, ~~`order:create`~~, `order:cancel`, `user:Field(Seller, Admin)`
- review schema (`rating [0, 64)`, `comment? String`) (underway)
- add shipping address, payment method (not saved to server due to privacy concerns)
- notifications (not priority) (underway)
- wishlist (not priority)
- integrate blockchain (not priority)
